utils: add lnxcstm utility for toolkit configuration
Signed-off-by: Dharshan P <dharshandandy@gmail.com>

diff --git a/git b/git
--- a/git
+++ b/git
@@ -3,20 +3,34 @@
 # CommandGuard
 # Prevent execution of dangerous git commands without confirmation.
 
+# Check this cutomization is enabled.
+enabled=$(lnxcstm git -g -e)
+if [[ "$enabled" =~ "False" ]]; then
+	/usr/bin/git $@
+	exit
+fi
+
 CMD="$1"
 
 alert() {
     /usr/bin/git status
-    read -rn1 -p "$(echo -e "Do you want to continue \033[1;33m${CMD}\033[0m ? [Y/n]")" confirmation # Get the confirmation from user before initiate.
-    echo
-    if [[ ! "$confirmation" =~ ^[yY] ]]; then
-        echo "Abort git $CMD.."
-        exit 1
+    # Check confirmation is enabled.
+    confirmation_enable=$(lnxcstm git -g -c)
+    if [[ "$confirmation_enable" =~ "True" ]]; then
+	read -rn1 -p "$(echo -e "Do you want to continue \033[1;33m${CMD}\033[0m ? [Y/n]: ")" confirmation # Get the confirmation from user before initiate.
+    	echo
+    	if [[ ! "$confirmation" =~ ^[yY] ]]; then
+        	echo "Abort git $CMD.."
+        	exit 1
+	fi	
     fi
 
-    # Confirming User
-    echo "Authentication required to continue..."
-    sudo -vk || exit 1 
+    # Authenticate User
+    authentication_enable=$(lnxcstm git -g -a)
+    if [[ "$authentication_enable" =~ "True" ]]; then
+    	echo "Authentication required to continue.."
+	sudo -vk || exit 1
+    fi
 }
 
 case "$CMD" in
diff --git a/rm b/rm
--- a/rm
+++ b/rm
@@ -1,5 +1,12 @@
 #!/bin/bash
 
+# Check this cutomization is enabled.
+enabled=$(lnxcstm rm -g -e)
+if [[ "$enabled" =~ "False" ]]; then
+	/usr/bin/rm $@
+	exit
+fi
+
 function MovetoTrash(){
 	local file="$1"
 	local counter=$(printf "$(date +%s | rev | cut -c 1-3 | rev)$(date +%N | rev | cut -c 1-2 | rev)")
@@ -14,13 +21,24 @@ function MovetoTrash(){
 	touch "$trash_files_path" # Modify the modification time of the moved files..
 }
 
-read -n1 -p "Are you sure want move the specified files or folder to Trash [Y|n] : " confirmation # Get the Confirmation From User Before starting Process.
-echo;
-
-if [[ ! "$confirmation" =~ ^[Yy] ]]; then
-	echo "Abort this Process.."
-	exit 1
+# Check confirmation is enabled.
+confirmation_enable=$(lnxcstm rm -g -c)
+if [[ "$confirmation_enable" =~ "True" ]]; then
+	read -n1 -p "Are you sure want move the specified files or folder to Trash [Y|n] : " confirmation # Get the Confirmation From User Before starting Process.
+	echo;
+	if [[ ! "$confirmation" =~ ^[Yy] ]]; then
+		echo "Abort this Process.."
+		exit 1
+	fi
 fi
+
+# Authenticate User
+authentication_enable=$(lnxcstm rm -g -a)
+if [[ "$authentication_enable" =~ "True" ]]; then
+	echo "Authentication required to continue.."
+	sudo -vk || exit 1
+fi
+
 for target in "$@"; do
 	if [[ ! $target =~ ^-[rfvid]+$ ]]; then
 		if [[ -a $(pwd)/$target ]]; then
